AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Foodie2ue notification service

Parameters:
  SESIdentityName:
    Type: String
    Default: "foodie2ue.com"

Globals:
  Function:
    Timeout: 5
    Runtime: python3.9

Resources:
  SendNotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/notifications/
      Handler: app.handler
      Policies:
        - SESCrudPolicy:
            IdentityName: !Ref SESIdentityName
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "ses:SendEmail"
              Resource: "*"
