AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Foodie2ue serverless backend.

Parameters:
  Stage:
    Type: String
    Default: dev
  Service:
    Type: String
    Default: foodie2ue

Resources:
  EventBus:
    Type: AWS::Serverless::Application
    Properties:
      Location: eventbus/template.yaml
      Parameters:
        Stage: !Ref Stage
        Service: !Ref Service
      Tags:
        service: !Ref Service
        stage: !Ref Stage

  Security:
    Type: AWS::Serverless::Application
    Properties:
      Location: security/template.yaml
      Parameters:
        EventBusPolicyArn: !GetAtt EventBus.Outputs.EventBusPolicyArn
      Tags:
        service: !Ref Service
        stage: !Ref Stage

  NotificationsService:
    Type: AWS::Serverless::Application
    Properties:
      Location: notifications/template.yaml
      Parameters:
        EventBusName: !GetAtt EventBus.Outputs.EventBusName
      Tags:
        service: !Ref Service
        stage: !Ref Stage

Outputs:
  EventBusArn:
    Description: Application EventBus ARN
    Value: !GetAtt EventBus.Outputs.EventBusArn
