AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Foodie2ue notification service

Parameters:
  CommonLayerARN:
    Type: String
  EventBusName:
    Type: String
  DefaultFromAddress:
    Type: String

Globals:
  Function:
    CodeUri: src/
    Runtime: python3.9
    Timeout: 5
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: notifications
        LOG_LEVEL: INFO
        DEFAULT_FROM_ADDRESS: !Ref DefaultFromAddress

Resources:
  SendNotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handle_notification
      Layers:
        - !Ref CommonLayerARN
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "ses:SendEmail"
                - "ses:SendRawEmail"
              Resource: "*"
      Events:
        NewOrderRule:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type:
                - OrderCreatedEvent
