AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: IAM and security resources

Parameters:
  EventBusPolicyArn:
    Type: String

Resources:
  EventBridgeUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - !Sub ${EventBusPolicyArn}
