AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Common layer for Lambda functions

Resources:
  CommonServicesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: makefile

Outputs:
  CommonLayerARN:
    Description: ARN for the common services Lambda layer
    Value: !Ref CommonServicesLayer
